---
title: "geom-data"
author: "Dane Skabelund"
date: "5/30/2017"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
```

## Viewing first data

```{r, warning=FALSE}
library(dplyr)
library(readr)


bety_src <- src_postgres(dbname = "bety", 
                         password = 'bety', 
                         host = 'terra-bety.default', 
                         user = 'bety', 
                         port = 5432)

traits <- tbl(bety_src, 'traits')

variables <- tbl(bety_src, 'variables') %>%
  mutate(variable_id = id)

sites <- tbl(bety_src, 'sites') %>%
  mutate(site_id = id)

big_table <- traits %>%
  left_join(variables, by = 'variable_id') %>% 
  left_join(sites, by = 'site_id')
  


z<-big_table %>%
  filter(name == 'plant_height'&!is.null(date)) %>%
  collect %>% 
  select(site_id,cultivar_id, date, mean)


library(ggplot2)

indoor_plot <- ggplot(data = z , aes(date, mean, group = site_id))+
  geom_point(size = 0.1, alpha = 0.2) +
  geom_smooth(method = "lm", se=FALSE, size = 0.1, alpha = 0.2) +
  facet_wrap(~cultivar_id, scales = 'free_x') +
  labs(y = "plant_height")

ggsave(filename="./indoor_plots/lm_by_cultivar.png", plot=indoor_plot)

```


```{r}



```





```{r}


my_cultivars <- big_table %>%
  filter(name == 'plant_height') %>%
  select(cultivar_id) %>% 
  collect(n=Inf) %>% 
  distinct


my_cultivars <- my_cultivars$cultivar_id


my_cultivars[1] %in% my_cultivars

for(tname in c('height','plant_height') ){
  big_table %>%
    filter(name == tname, cultivar_id %in% my_cultivars) %>%
    select(name,date,mean,sitename,greenhouse,city,cultivar_id,site_id) %>% 
    collect(n = Inf) %>% 
    write_csv(path = paste0("~/Indoor-Outdoor/data/",tname,".csv"))
}



my_outdoor_data <- big_table %>%
  filter(name == 'height', cultivar_id %in% my_cultivars) %>%
  select(name,cultivar_id) %>% 
  collect(n=Inf)

my_outdoor_data


```




aa <- big_table %>%
  filter(name == 'height') %>%
  select(cultivar_id) %>% 
  collect(n=Inf) %>% 
  unique

aa


# download traits we want to /data/*.csv





big_table %>%
  filter(name == 'plant_height') %>%
  collect(n=Inf) %>%
  dim()













my_outdoor_data <- big_table %>%
  filter(name == 'height', cultivar_id %in% my_cultivars) %>%
  select(name,cultivar_id) %>% 
  collect(n=Inf)

my_outdoor_data


